plugin: aws_ec2
regions:
  - ap-south-1

filters:
  tag:Role: webserver
  instance-state-name: running

keyed_groups:
  - key: tags.Role
  - key: tags.Env

hostnames:
  - ip-address

compose:
  ansible_user: "'ubuntu'"
